# Generated by Django 3.0.6 on 2020-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='categoryid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
