# Generated by Django 3.0.6 on 2020-05-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200519_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='show',
        ),
    ]
