# Generated by Django 3.0.6 on 2020-05-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200520_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='body_txt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='summary',
            new_name='short_txt',
        ),
    ]
