# Generated by Django 3.0.6 on 2020-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
