# Generated by Django 3.0.6 on 2020-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
