# Generated by Django 3.0.6 on 2020-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200516_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='abouttxt',
        ),
        migrations.RemoveField(
            model_name='main',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='main',
            name='link',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picname2',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picurl',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picurl2',
        ),
        migrations.RemoveField(
            model_name='main',
            name='set_name',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tell',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tw',
        ),
        migrations.RemoveField(
            model_name='main',
            name='yt',
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.TextField(),
        ),
    ]
