# Generated by Django 3.0.6 on 2020-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200516_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='git',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='insta',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='linkd',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='steam',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.TextField(default='-'),
        ),
    ]
