# Generated by Django 3.0.6 on 2020-05-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200518_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='insta',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='linkd',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='tw',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='yt',
            new_name='youtube',
        ),
    ]
