# Generated by Django 3.0.6 on 2020-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200518_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='git',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='instagram',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='linkedin',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='steam',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='youtube',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
